import { INewOccupationGroupSpec, OccupationGroupType } from "esco/occupationGroup/OccupationGroup.types";

export const expected: Omit<INewOccupationGroupSpec, "modelId">[] = [
  {
    originUri: "origin uri",
    UUIDHistory: [],
    code: "01",
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2"],
    description: "description",
    groupType: OccupationGroupType.ISCOGroup,
    importId: "key_1",
  },
  {
    originUri: "esco\nuri\nwith\nlinebreak",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf8d", "b69710e0-7e7d-43ea-a645-26dab12faf83"],
    code: "0101",
    preferredLabel: "preferred\nlabel\nwith\nlinebreak",
    altLabels: ["label1", "label2"],
    groupType: OccupationGroupType.ISCOGroup,
    description: "description\nwith\nlinebreak",
    importId: "key_2",
  },
  {
    originUri: "",
    UUIDHistory: ["632b3cac-515f-4260-b1d9-ea8674d5ded2"],
    code: "",
    preferredLabel: "",
    altLabels: [],
    groupType: OccupationGroupType.ISCOGroup,
    description: "",
    importId: "key_3",
  },
  {
    originUri: "origin uri",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf8d", "b69710e0-7e7d-43ea-a645-26dab12faf56"],
    code: "0102",
    preferredLabel: "duplicate altLabels",
    altLabels: ["label1", "label2"],
    groupType: OccupationGroupType.ISCOGroup,
    description: "description",
    importId: "key_4",
  },
  {
    originUri: "origin uri",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf8f"],
    code: "I0102",
    preferredLabel: "not duplicate altLabels",
    altLabels: ["label I0102"],
    description: "description",
    groupType: OccupationGroupType.ISCOGroup,
    importId: "key_i4",
  },
  {
    originUri: "icatus urn",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf8g"],
    code: "I0103",
    preferredLabel: "ICATUS Occupation group",
    altLabels: ["label I0103"],
    description: "description",
    groupType: OccupationGroupType.ICATUSGroup,
    importId: "key_i5",
  },
];
