import { INewOccupationSpec } from "esco/occupation/occupation.types";
import { OccupationType } from "esco/common/objectTypes";

export const expected: Omit<INewOccupationSpec, "modelId">[] = [
  {
    ESCOUri: "esco uri",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf83", "b69710e0-7e7d-43ea-a645-26dab12faf8d"],
    ISCOGroupCode: "01",
    code: "0001.1.2.3_01",
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2"],
    description: "description",
    definition: "definition",
    scopeNote: "scope note",
    regulatedProfessionNote: "regulated profession note",
    importId: "key_1",
    occupationType: OccupationType.LOCAL,
  },
  {
    ESCOUri: "esco\nuri\nwith\nlinebreak",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf83", "b69710e0-7e7d-43ea-a645-26dab12faf8d"],
    ISCOGroupCode: "0101",
    code: "0101.01.02.03_01",
    preferredLabel: "preferred\nlabel\nwith\nlinebreak",
    altLabels: ["label1", "label2"],
    description: "description\nwith\nlinebreak",
    definition: "definition\nwith\nlinebreak",
    scopeNote: "scope\nnote\nwith\nlinebreak",
    regulatedProfessionNote: "regulated\nprofession\nnote\nwith\nlinebreak",
    importId: "key_2",
    occupationType: OccupationType.LOCAL,
  },
  {
    ESCOUri: "esco uri",
    UUIDHistory: [],
    ISCOGroupCode: "01",
    code: "0001.1.2.3_01",
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2"],
    description: "description",
    definition: "definition",
    scopeNote: "scope note",
    regulatedProfessionNote: "regulated profession note",
    importId: "key_7",
    occupationType: OccupationType.LOCAL,
  },

  {
    ESCOUri: "esco uri",
    UUIDHistory: [],
    ISCOGroupCode: "01",
    code: "0101.01.02.04_01",
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2"],
    description: "description",
    definition: "definition",
    scopeNote: "scope note",
    regulatedProfessionNote: "regulated profession note",
    importId: "key_8",
    occupationType: OccupationType.LOCAL,
  },
];
