import { INewOccupationSpec } from "esco/occupations/occupation.types";
import { ObjectTypes } from "esco/common/objectTypes";

export const expected: Omit<INewOccupationSpec, "modelId">[] = [
  {
    originUri: "origin uri",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf83", "b69710e0-7e7d-43ea-a645-26dab12faf8d"],
    occupationGroupCode: "01",
    code: "0001.1.2.3",
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2", "preferred label"],
    description: "description",
    definition: "definition",
    scopeNote: "scope note",
    regulatedProfessionNote: "regulated profession note",
    importId: "key_1",
    occupationType: ObjectTypes.ESCOOccupation,
    isLocalized: false,
  },
  {
    originUri: "origin\nuri\nwith\nlinebreak",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf83", "b69710e0-7e7d-43ea-a645-26dab12faf8d"],
    occupationGroupCode: "0101",
    code: "0101.01.02.03_01",
    preferredLabel: "preferred\nlabel\nwith\nlinebreak",
    altLabels: ["label1", "label2"],
    description: "description\nwith\nlinebreak",
    definition: "definition\nwith\nlinebreak",
    scopeNote: "scope\nnote\nwith\nlinebreak",
    regulatedProfessionNote: "regulated\nprofession\nnote\nwith\nlinebreak",
    importId: "key_2",
    occupationType: ObjectTypes.LocalOccupation,
    isLocalized: false,
  },
  {
    originUri: "origin uri",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf83", "b69710e0-7e7d-43ea-a645-26dab12faf8d"],
    occupationGroupCode: "01",
    code: "1000.1.2.3",
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2", "preferred label"],
    description: "description",
    definition: "definition",
    scopeNote: "scope note",
    regulatedProfessionNote: "regulated profession note",
    importId: "key_3",
    occupationType: ObjectTypes.ESCOOccupation,
    isLocalized: true,
  },
  {
    originUri: "origin uri",
    UUIDHistory: [],
    occupationGroupCode: "01",
    code: "0001.1.2.3.4_01",
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2", "preferred label"],
    description: "description",
    definition: "definition",
    scopeNote: "scope note",
    regulatedProfessionNote: "regulated profession note",
    importId: "key_4",
    occupationType: ObjectTypes.LocalOccupation,
    isLocalized: false,
  },
  {
    originUri: "origin uri",
    UUIDHistory: [],
    occupationGroupCode: "I01",
    code: "0001.1.2.3.4_01",
    preferredLabel: "preferred label",
    altLabels: ["label1", "preferred label"],
    description: "description",
    definition: "definition",
    scopeNote: "scope note",
    regulatedProfessionNote: "regulated profession note",
    importId: "key_i4",
    occupationType: ObjectTypes.LocalOccupation,
    isLocalized: false,
  },
];
