import { INewOccupationSpecLocalized } from "esco/occupations/_shared/occupation.types";
import { ObjectTypes } from "esco/common/objectTypes";
import { ITranslatedStringDoc, ITranslatedStringArrayDoc } from "common/language/translatedString.types";
import LanguageAPISpecs from "api-specifications/language";

const en = "en" as LanguageAPISpecs.Types.LanguageDbKeyName;
const toTranslatedString = (value: string): ITranslatedStringDoc => new Map([[en, value]]);
const toTranslatedStringArray = (values: string[]): ITranslatedStringArrayDoc => values.map((v) => new Map([[en, v]]));

export const expected: Omit<INewOccupationSpecLocalized, "modelId">[] = [
  {
    originUri: "origin uri",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf83", "b69710e0-7e7d-43ea-a645-26dab12faf8d"],
    occupationGroupCode: "01",
    code: "0001.1.2.3",
    preferredLabel: toTranslatedString("preferred label"),
    altLabels: toTranslatedStringArray(["label1", "label2", "preferred label"]),
    description: toTranslatedString("description"),
    definition: toTranslatedString("definition"),
    scopeNote: toTranslatedString("scope note"),
    regulatedProfessionNote: toTranslatedString("regulated profession note"),
    importId: "key_1",
    occupationType: ObjectTypes.ESCOOccupation,
    isLocalized: false,
  },
  {
    originUri: "origin\nuri\nwith\nlinebreak",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf83", "b69710e0-7e7d-43ea-a645-26dab12faf8d"],
    occupationGroupCode: "0101",
    code: "0101.01.02.03_01",
    preferredLabel: toTranslatedString("preferred\nlabel\nwith\nlinebreak"),
    altLabels: toTranslatedStringArray(["label1", "label2"]),
    description: toTranslatedString("description\nwith\nlinebreak"),
    definition: toTranslatedString("definition\nwith\nlinebreak"),
    scopeNote: toTranslatedString("scope\nnote\nwith\nlinebreak"),
    regulatedProfessionNote: toTranslatedString("regulated\nprofession\nnote\nwith\nlinebreak"),
    importId: "key_2",
    occupationType: ObjectTypes.LocalOccupation,
    isLocalized: false,
  },
  {
    originUri: "origin uri",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf83", "b69710e0-7e7d-43ea-a645-26dab12faf8d"],
    occupationGroupCode: "01",
    code: "1000.1.2.3",
    preferredLabel: toTranslatedString("preferred label"),
    altLabels: toTranslatedStringArray(["label1", "label2", "preferred label"]),
    description: toTranslatedString("description"),
    definition: toTranslatedString("definition"),
    scopeNote: toTranslatedString("scope note"),
    regulatedProfessionNote: toTranslatedString("regulated profession note"),
    importId: "key_3",
    occupationType: ObjectTypes.ESCOOccupation,
    isLocalized: true,
  },
  {
    originUri: "origin uri",
    UUIDHistory: [],
    occupationGroupCode: "01",
    code: "0001.1.2.3.4_01",
    preferredLabel: toTranslatedString("preferred label"),
    altLabels: toTranslatedStringArray(["label1", "label2", "preferred label"]),
    description: toTranslatedString("description"),
    definition: toTranslatedString("definition"),
    scopeNote: toTranslatedString("scope note"),
    regulatedProfessionNote: toTranslatedString("regulated profession note"),
    importId: "key_4",
    occupationType: ObjectTypes.LocalOccupation,
    isLocalized: false,
  },
  {
    originUri: "origin uri",
    UUIDHistory: [],
    occupationGroupCode: "I01",
    code: "0001.1.2.3.4_01",
    preferredLabel: toTranslatedString("preferred label"),
    altLabels: toTranslatedStringArray(["label1", "preferred label"]),
    description: toTranslatedString("description"),
    definition: toTranslatedString("definition"),
    scopeNote: toTranslatedString("scope note"),
    regulatedProfessionNote: toTranslatedString("regulated profession note"),
    importId: "key_i4",
    occupationType: ObjectTypes.LocalOccupation,
    isLocalized: false,
  },
];
