export const Routes = {
  APPLICATION_INFO_ROUTE: "/info",
  MODELS_ROUTE: "/models",
  PRESIGNED_ROUTE: "/presigned",
  IMPORT_ROUTE: "/import",
  EXPORT_ROUTE: "/export",
  OCCUPATIONS_ROUTE: "/models/:modelId/occupations",
  OCCUPATION_ROUTE: "/models/:modelId/occupations/:id",
  OCCUPATION_GROUPS_ROUTE: "/models/:modelId/occupationGroups",
  OCCUPATION_GROUP_ROUTE: "/models/:modelId/occupationGroups/:id",
  OCCUPATION_GROUP_PARENT_ROUTE: "/models/:modelId/occupationGroups/:id/parent",
  OCCUPATION_GROUP_CHILDREN_ROUTE: "/models/:modelId/occupationGroups/:id/children",
  SKILL_GROUPS_ROUTE: "/models/:modelId/skillGroups",
  SKILL_GROUP_ROUTE: "/models/:modelId/skillGroups/:id",
  SKILLS_ROUTE: "/models/:modelId/skills",
  SKILL_ROUTE: "/models/:modelId/skills/:id",
  OCCUPATION_PARENT_ROUTE: "/models/:modelId/occupations/:id/parent",
  OCCUPATION_CHILDREN_ROUTE: "/models/:modelId/occupations/:id/children",
  OCCUPATION_SKILLS_ROUTE: "/models/:modelId/occupations/:id/skills",
  SKILL_PARENTS_ROUTE: "/models/:modelId/skills/:id/parents",
  SKILL_CHILDREN_ROUTE: "/models/:modelId/skills/:id/children",
  SKILL_OCCUPATIONS_ROUTE: "/models/:modelId/skills/:id/occupations",
  SKILL_RELATED_ROUTE: "/models/:modelId/skills/:id/related",
};
