name: 'Update aws'
description: 'Update a aws lambda-update'
inputs:
  function-name:  # name of the s3 bucket
    description: 'The name of the lambda'
    required: true
runs:
  using: "composite"
  steps:
    - id: zip AWS lambda Deploy
      run: |
        echo ${{inputs.function-name}}
        zip -r9 ./backend/deploy/${{inputs.function-name}}/index.zip ./backend/source/${{inputs.function-name}}/
    - id: AWS Deploy
      run: |
        aws lambda update-function-code --function-name ${{inputs.function-name}} --zip-file fileb://backend/deploy/${{inputs.function-name}}/index.zip 
        