name: 'Update aws'
description: 'Update a aws lambda-update'
inputs:
  function-name:
    description: 'The name of the lambda'
    required: true
runs:
  using: "composite"
  steps:
    - id: zip-aws-lambda-deploy
      shell: bash
      run: |
        echo ${{ inputs.function-name }}
        mkdir -p ./backend/deploy/
        cd ./backend/build/
        zip -r9 ../deploy/index.zip *
    - id: aws-deploy
      shell: bash
      run: |
        aws lambda update-function-code --function-name ${{ inputs.function-name }} --zip-file fileb://backend/deploy/index.zip 
        aws lambda wait function-updated --function-name ${{ inputs.function-name }} 
        aws lambda update-function-configuration --function-name ${{ inputs.function-name }} --environment Variables={NODE_OPTIONS='--enable-source-maps'}
        aws lambda wait function-updated --function-name ${{ inputs.function-name }}