name: 'Update s3 bucket'
description: 'Update a s3 bucket'
inputs:
  bucket-name:  # name of the s3 bucket
    description: 'The name of the s3 bucket'
    required: true
runs:
  using: "composite"
  steps:
    - id: aws-deploy
      shell: bash
      run: aws s3 sync ./frontend/build/. s3://${{ inputs.bucket-name }}