export const expected = [
  {
    ESCOUri: "",
    originUUID: "",
    preferredLabel: "",
    altLabels: [],
    description: "",
    scopeNote: "",
    definition: "",
    skillType: "",
    reuseLevel: "",
  },
  {
    ESCOUri: "",
    originUUID: "",
    preferredLabel: "",
    altLabels: [],
    description: "",
    scopeNote: "",
    definition: "",
    skillType: "",
    reuseLevel: "",
  },
  {
    ESCOUri: "esco uri",
    originUUID: "origin uuid",
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2"],
    description: "description",
    scopeNote: "scopeNote",
    definition: "definition",
    skillType: "skill/competence",
    reuseLevel: "sector-specific",
  },
  {
    ESCOUri: "esco\nuri\nwith\nlinebreak",
    originUUID: "origin\nuuid\nwith\nlinebreak",
    preferredLabel: "preferred\nlabel\nwith\nlinebreak",
    altLabels: ["label1", "label2"],
    description: "description\nwith\nlinebreak",
    definition: "definition\nwith\nlinebreak",
    scopeNote: "scopeNote\nwith\nlinebreak",
    skillType: "knowledge",
    reuseLevel: "cross-sector",
  }
];