import { INewSkillSpec, ReuseLevel, SkillType } from "esco/skill/skills.types";

export const expected: Omit<INewSkillSpec, "modelId">[] = [
  {
    originUri: "origin uri",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf8d", "b69710e0-7e7d-43ea-a645-26dab12faf83"],
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2", "preferred label"],
    description: "description",
    scopeNote: "scopeNote",
    definition: "definition",
    skillType: SkillType.SkillCompetence,
    reuseLevel: ReuseLevel.SectorSpecific,
    importId: "key_1",
  },
  {
    originUri: "origin\nuri\nwith\nlinebreak",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf8d"],
    preferredLabel: "preferred\nlabel\nwith\nlinebreak",
    altLabels: ["label1", "label2"],
    description: "description\nwith\nlinebreak",
    definition: "definition\nwith\nlinebreak",
    scopeNote: "scopeNote\nwith\nlinebreak",
    skillType: SkillType.Knowledge,
    reuseLevel: ReuseLevel.CrossSector,
    importId: "key_2",
  },
  {
    originUri: "",
    UUIDHistory: [],
    preferredLabel: "",
    altLabels: [],
    description: "",
    definition: "",
    scopeNote: "",
    skillType: SkillType.None,
    reuseLevel: ReuseLevel.None,
    importId: "key_3",
  },
  {
    originUri: "origin uri",
    UUIDHistory: [],
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2", "preferred label"],
    description: "description",
    scopeNote: "scopeNote",
    definition: "definition",
    skillType: SkillType.SkillCompetence,
    reuseLevel: ReuseLevel.SectorSpecific,
    importId: "key_4",
  },
  {
    originUri: "origin uri",
    UUIDHistory: [],
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2", "preferred label"],
    description: "description",
    scopeNote: "scopeNote",
    definition: "definition",
    skillType: SkillType.SkillCompetence,
    reuseLevel: ReuseLevel.SectorSpecific,
    importId: "key_5",
  },
  {
    originUri: "origin uri",
    UUIDHistory: ["b69710e0-7e7d-43ea-a645-26dab12faf8d", "b69710e0-7e7d-43ea-a645-26dab12faf56"],
    preferredLabel: "duplicate altLabels",
    altLabels: ["label1", "label2", "duplicate altLabels"],
    description: "description",
    scopeNote: "scopeNote",
    definition: "definition",
    skillType: SkillType.SkillCompetence,
    reuseLevel: ReuseLevel.SectorSpecific,
    importId: "key_8",
  },
  {
    originUri: "origin uri",
    UUIDHistory: [],
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2", "preferred label"],
    description: "description",
    scopeNote: "scopeNote",
    definition: "definition",
    skillType: SkillType.SkillCompetence,
    reuseLevel: ReuseLevel.SectorSpecific,
    importId: "key_9",
  },
  {
    originUri: "origin uri",
    UUIDHistory: [],
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2", "preferred label"],
    description: "description",
    scopeNote: "scopeNote",
    definition: "definition",
    skillType: SkillType.SkillCompetence,
    reuseLevel: ReuseLevel.SectorSpecific,
    importId: "key_10",
  },
  {
    originUri: "origin uri",
    UUIDHistory: [],
    preferredLabel: "preferred label",
    altLabels: ["label1", "label2", "preferred label"],
    description: "description",
    scopeNote: "scopeNote",
    definition: "definition",
    skillType: SkillType.SkillCompetence,
    reuseLevel: ReuseLevel.SectorSpecific,
    importId: "key_11",
  },
];
