name: Request approval

on:
  workflow_call:
    inputs:
      tested-version:
        required: true
        type: string
      backend-url:
        required: true
        type: string

jobs:
  approve:
    runs-on: ubuntu-latest
    environment: confirmation
    steps:
      - name: Request approval
        run: echo "Deployment approved"

  db-sanity-checks:
    needs: approve
    uses: ./.github/workflows/db-sanity-checks.yml
    secrets: inherit
    with:
      command: assert
      backend-url: ${{ github.event.inputs.backend-url }}
      version: ${{ github.event.inputs.tested-version }}
