name: Request approval

on:
  workflow_call:

jobs:
  approve:
    runs-on: ubuntu-latest
    environment: confirmation
    steps:
      - name: Request approval
        run: echo "Deployment approved"

  db-sanity-checks:
    needs: approve
    uses: ./.github/workflows/db-sanity-checks.yml
    secrets: inherit
    with:
      command: assert
