name: Deploy Locales Bucket

on:
  workflow_call:

jobs:
  approve:
    runs-on: ubuntu-latest
    environment: confirmation
    steps:
      - name: Request approval
        run: echo "Deployment approved"

