name: Deploy Backend

on:
  workflow_call:
    inputs:
      version-info:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    name: Deploy and test the backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: backend/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: backend
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - name: Download backend.build.folder
        uses: actions/download-artifact@v3
        with:
          name: backend.build.folder
          path: backend/build/
      - name: Update Info Lambda Function
        uses: ./.github/aws-lambda-actions/
        with:
          function-name: info
      - name: Smoke Tests
        run: |
          echo '${{ inputs.version-info }}' > ./src/info/version.json
          cat ./src/info/version.json
          yarn run test:smoke
        working-directory: backend