name: deploy to lambda
on: [push]

permissions:
  contents: read
  checks: write

jobs:
  release:
    name: Deploy lambda function
    runs-on: [ ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        role-duration-seconds: 1200
        role-session-name: MySessionName
    - name: zip Lambda Function
      run: |
        echo $GITHUB_SHA   
        # changing the verions    
        sed -i -e "s|\###date###|$(date -u +%F' %T.%3N UTC')|g" version.json
        sed -i -e "s|\###GITHUB_REF_NAME###|$GITHUB_REF_NAME|g" version.json
        sed -i -e "s|\###GITHUB_RUN_NUMBER###|$GITHUB_RUN_NUMBER|g" version.json
        sed -i -e "s|\###GITHUB_SHA###|$GITHUB_SHA|g" version.json
        zip index.zip index.js
    - name: AWS Deploy
      run: |
        aws lambda update-function-code --function-name testtabiya --zip-file fileb://index.zip
