name: deploy to lambda
on: [push]

permissions:
  contents: read
  checks: write

jobs:
  release:
    name: Deploy lambda function
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        role-duration-seconds: 1200
        role-session-name: MySessionName
    - name: Set Version Info
      run: |
        ./pipeline/setVersionInfo.sh ./backend/source/info/version.json
        cat ./backend/source/info/version.json
    - name: Update Info Lambda Function
      uses: ./.github/aws-lambda-actions/
      with:
          function-name: info
#    - name: zip Info Lambda Function
#      run: |
#        zip -r9 ./backend/deploy/info/index.zip ./backend/source/info/
#    - name: AWS Deploy
#      run: |
#        aws lambda update-function-code --function-name info --zip-file fileb://backend/deploy/info/index.zip
