name: Build Frontend

on:
  workflow_call:
    outputs:
      version-info:
        description: 'The frontend version info'
        value: ${{ jobs.build.outputs.version-info }}
    inputs:
      environment:
        required: true
        type: string
      target-domain-name:
        required: true
        type: string
      frontend-url:
        required: true
        type: string
      backend-url:
        required: true
        type: string
      auth-url:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version-info: ${{ steps.setVersionInfo.outputs.version-info }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Echo inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Target Domain Name: ${{ inputs.target-domain-name }}"
          echo "Frontend URL: ${{ inputs.frontend-url }}"
          echo "Backend URL: ${{ inputs.backend-url }}"
          echo "Auth URL: ${{ inputs.auth-url }}"
      - name: Install dependencies
        run: yarn install
        working-directory: frontend
      - name: Set Version Info
        id: setVersionInfo
        # see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        # for multiline strings
        run: |
          ./pipeline/setVersionInfo.sh frontend/public/data/version.json
          cat frontend/public/data/version.json
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "version-info<<$EOF" >> "$GITHUB_OUTPUT"
          echo "$(cat ./frontend/public/data/version.json)" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
      - name: Lint
        run: yarn run lint
        working-directory: frontend
      - name: Build
        run: yarn run build
        working-directory: frontend
      - name: Archive build bundle
        uses: actions/upload-artifact@v3
        with:
          name: frontend.build.folder
          path: frontend/build/
          retention-days: 1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: frontend
      - name: Test
        run: yarn run test
        working-directory: frontend
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: frontend.lcov.info
          path: frontend/coverage/lcov.info
          retention-days: 1
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: frontend
      - name: Accessibility Tests
        run: yarn run build-storybook && yarn run test:accessibility
        working-directory: frontend
