name: Build Frontend

on:
  workflow_call:
    outputs:
      version-info:
        description: 'The frontend version info'
        value: ${{ jobs.build.outputs.version-info }}
    inputs:
      backend-url:
        required: true
        type: string
      auth-url:
        required: true
        type: string
      cognito-client-id:
        required: true
        type: string
      cognito-client-secret:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version-info: ${{ steps.setVersionInfo.outputs.version-info }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Build env.js file
        # we are basically creating a js file with the passed env variables
        # that can be executed in the client browser when the js file is loaded
        run: |
          echo "window.tabiyaConfig = {" > frontend/public/data/env.js
          echo "\"BACKEND_URL\": btoa(\"${{ inputs.backend-url }}\")," >> frontend/public/data/env.js
          echo "\"AUTH_URL\": btoa(\"${{ inputs.auth-url }}\")," >> frontend/public/data/env.js
          echo "\"COGNITO_CLIENT_ID\": btoa(\"${{ inputs.cognito-client-id }}\")," >> frontend/public/data/env.js
          echo "\"COGNITO_CLIENT_SECRET\": btoa(\"${{ inputs.cognito-client-secret }}\")" >> frontend/public/data/env.js
          echo "};" >> frontend/public/data/env.js
          cat frontend/public/data/env.js
      - name: Install dependencies
        run: yarn install
        working-directory: frontend
      - name: Set Version Info
        id: setVersionInfo
        # see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        # for multiline strings
        run: |
          ./pipeline/setVersionInfo.sh frontend/public/data/version.json
          cat frontend/public/data/version.json
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "version-info<<$EOF" >> "$GITHUB_OUTPUT"
          echo "$(cat ./frontend/public/data/version.json)" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"
      - name: Lint
        run: yarn run lint
        working-directory: frontend
      - name: Build
        run: yarn run build
        working-directory: frontend
      - name: Archive build bundle
        uses: actions/upload-artifact@v3
        with:
          name: frontend.build.folder
          path: frontend/build/
          retention-days: 1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: frontend
      - name: Test
        run: yarn run test
        working-directory: frontend
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: frontend.lcov.info
          path: frontend/coverage/lcov.info
          retention-days: 1
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: frontend
      - name: Accessibility Tests
        run: yarn run build-storybook && yarn run test:accessibility
        working-directory: frontend
