name: Build Locales

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: locales/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: locales
      - name: Lint
        run: yarn run lint
        working-directory: locales
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: locales/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: locales
      - name: Test
        run: yarn run test
        working-directory: locales
