name: MongoDB Database Dump and Restore

on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string

jobs:
  dump-and-restore:
    name: Database Dump and Restore
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up MongoDB CLI Tools
        run: |
          sudo apt update
          curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-8.0.gpg
          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-database-tools
          mongodump --version

      - name: Dump MongoDB Database
        env:
          SOURCE_DB_URL: ${{ secrets.PROD_MONGODB_URI }}
        run: |
          mongodump --uri="${SOURCE_DB_URL}" --out=/tmp/mongodump --compressors=snappy

      - name: Restore MongoDB Database
        env:
          TARGET_DB_URL: ${{ secrets.MONGODB_URI }}
        run: |
          export TARGET_FOLDER=$(for dir in /tmp/mongodump/*/; do basename "$dir"; done)
          echo "Restoring database from /tmp/mongodump/${TARGET_FOLDER}"
          ls /tmp/mongodump
          mongorestore --uri="${TARGET_DB_URL}" /tmp/mongodump/${TARGET_FOLDER} --drop --numInsertionWorkersPerCollection=20 --noIndexRestore --compressors=snappy --numParallelCollections=10
