name: Database Sanity Checks

on:
  workflow_call:
    outputs:
      testing-backend-version:
        description: 'The version of the backend to be tested'
        value: ${{ jobs.db-sanity-checks.outputs.testing-backend-version }}
    inputs:
      command:
        required: true
        type: string
      backend-url:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  db-sanity-checks:
    runs-on: ubuntu-latest
    outputs:
      testing-backend-version: ${{ steps.get-current-version.outputs.testing-backend-version }}
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
        working-directory: pipeline/scripts
      - name: Run Database Sanity Checks ${{ inputs.command }}
        id: get-current-version
        run: |
          node ./db-sanity-checks.js ${{ inputs.command }} ${{ inputs.backend-url }}/info
        working-directory: pipeline/scripts

