name: Deploy Frontend

on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
      version-info:
        required: true
        type: string
      target-domain-name:
        required: true
        type: string
    outputs:
      frontendBucketWebsiteURLBase:
        description: "The frontend bucket url"
        value: ${{ jobs.deploy.outputs.frontendBucketWebsiteURLBase }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    outputs:
      frontendBucketWebsiteURLBase: ${{ steps.pulumi.outputs.frontendBucketWebsiteURLBase }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: iac/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: iac
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - name: Download frontend.build.folder
        uses: actions/download-artifact@v4
        with:
          name: frontend.build.folder
          path: frontend/build/
      - name: Deploy frontend
        id: pulumi
        uses: pulumi/actions@v5
        with:
          work-dir: iac/frontend
          command: up
          stack-name: tabiya-tech/taxonomy-model-application-frontend/${{ inputs.target-environment }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DOMAIN_NAME: ${{ inputs.target-domain-name }}
