name: Deploy Common Infrastructure

on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
      frontend-version-info:
        required: true
        type: string
      backend-version-info:
        required: true
        type: string
    outputs:
      frontendURLBase:
        description: "The frontend url"
        value: ${{ jobs.deploy.outputs.frontendURLBase }}
      backendURLBase:
        description: "The backend url"
        value: ${{ jobs.deploy.outputs.backendURLBase }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    outputs:
      backendURLBase: ${{ steps.pulumi.outputs.backendURLBase }}
      frontendURLBase: ${{ steps.pulumi.outputs.frontendURLBase }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: iac/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: iac
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - name: Deploy Common Infrastructure
        id: pulumi
        uses: pulumi/actions@v4
        with:
          work-dir: iac/common
          command: up
          stack-name: tabiya-tech/taxonomy-model-application-common/${{ github.event.pull_request.head.ref }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}