name: E2E Test

on:
  workflow_call:
    inputs:
      component:
        description: Either 'frontend' or 'backend'
        required: true
        type: string
      target-environment:
        required: true
        type: string
      backend-url:
        required: true
        type: string
      user-pool-id:
        required: true
        type: string
      cognito-client-id:
        required: true
        type: string
      cognito-client-secret:
        required: true
        type: string
jobs:
  test-api:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: ${{ inputs.component }}/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: backend
      - name: Run E2E Tests
        run: yarn run test:e2e
        working-directory: ${{ inputs.component }}
        env:
          BACKEND_URL: ${{ inputs.backend-url }}
          USER_POOL_ID: ${{ inputs.user-pool-id }}
          USER_POOL_CLIENT_ID: ${{ inputs.cognito-client-id }}
          USER_POOL_CLIENT_SECRET: ${{ inputs.cognito-client-secret }}
          TEST_MODEL_MANAGER_USERNAME: ${{ secrets.TEST_MODEL_MANAGER_USERNAME }}
          TEST_MODEL_MANAGER_PASSWORD: ${{ secrets.TEST_MODEL_MANAGER_PASSWORD }}
          TEST_REGISTERED_USER_USERNAME: ${{ secrets.TEST_REGISTERED_USER_USERNAME }}
          TEST_REGISTERED_USER_PASSWORD: ${{ secrets.TEST_REGISTERED_USER_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
