name: taxonomy application model

on:
  push:
    branches:
      - "fe-deployment"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Getting info
        run: |
          sed -i -e "s|\###date###|$(date -u +%F' %T.%3N UTC')|g" frontend/source/app.html
          sed -i -e "s|\###GITHUB_REF_NAME###|$GITHUB_REF_NAME|g" frontend/source/app.html
          sed -i -e "s|\###GITHUB_RUN_NUMBER###|$GITHUB_RUN_NUMBER|g" frontend/source/app.html
          sed -i -e "s|\###GITHUB_SHA###|$GITHUB_SHA|g" frontend/source/app.html
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1
            role-duration-seconds: 1200
            role-session-name: MySessionName
      - name: AWS S3 Deploy
        run: aws s3 sync ./frontend/source/. s3://tabiya-frontend-dev
