name: taxonomy application model
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Getting info
        run: ./pipeline/setVersionInfo.sh frontend/public/data/version.json
      - name: Install dependencies
        run: yarn install
        working-directory: frontend
      - name: Build
        run: yarn run build
        working-directory: frontend
      - name: Test
        run: yarn run test
        working-directory: frontend
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - name: AWS S3 Deploy
        uses: ./.github/aws-s3-actions/
        with:
          bucket-name: tabiya-frontend-dev
         
