name: Frontend CI

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    name: Build and test the frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: frontend
      - name: Set version info
        run: |
          ./pipeline/setVersionInfo.sh frontend/public/data/version.json
          cat frontend/public/data/version.json
      - name: Build
        run: yarn run build
        working-directory: frontend
      - name: Test
        run: yarn run test
        working-directory: frontend
### TODO move to separate job with a dependency on the build job
#### deploy_dev:
####   name: Deploy frontend to S3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - name: AWS S3 Deploy
        uses: ./.github/aws-s3-actions/
        with:
          bucket-name: tabiya-frontend-dev