name: Main CI
on:
  push:
  # branches:
  #   - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  # Backend
  build-backend:
    uses: ./.github/workflows/build-backend.yml
    secrets: inherit
  deploy-backend:
    if: github.event_name == 'push'
    needs: [ build-backend ]
    uses: ./.github/workflows/deploy-backend.yml
    secrets: inherit
    with:
      target-environment: dev
      version-info: ${{ needs.build-backend.outputs.version-info }}
  # Frontend
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    secrets: inherit
  deploy-frontend:
    if: github.event_name == 'push'
    needs: [ build-frontend ]
    uses: ./.github/workflows/deploy-frontend.yml
    secrets: inherit
    with:
      target-environment: dev
      version-info: ${{ needs.build-frontend.outputs.version-info }}
  # Sonarcloud
  sonarcloud:
    needs: [ build-backend, build-frontend ]
    uses: ./.github/workflows/sonar-cloud.yml
    secrets: inherit
  # Common Infrastructure
  deploy-common:
    if: github.event_name == 'push'
    needs: [ deploy-frontend, build-frontend, deploy-backend, build-backend ]
    uses: ./.github/workflows/deploy-common.yml
    secrets: inherit
    with:
      target-environment: dev
      frontend-version-info: ${{ needs.build-frontend.outputs.version-info }}
      backend-version-info: ${{ needs.build-backend.outputs.version-info }}

