name: Main CI

on:
  push:
  # branches:
  #   - main
  #pull_request:
  #  types: [ opened, synchronize, reopened ]

jobs:
  # Set-Up Infrastructure
  setup-infrastructure:
    uses: ./.github/workflows/deploy-setup.yml
    secrets: inherit
    with:
      target-environment: dev
  # API Specifications
  build-api-specs:
    uses: ./.github/workflows/build-api-specs.yml
    secrets: inherit
  # Auth
  deploy-auth:
    needs: [ setup-infrastructure, setup-infrastructure ]
    uses: ./.github/workflows/deploy-auth.yml
    secrets: inherit
    with:
      target-environment: dev
      target-domain-name: ${{ needs.setup-infrastructure.outputs.target-domain-name }}
#  # Locales
  build-locales:
    needs: [ build-api-specs ]
    uses: ./.github/workflows/build-locales.yml
    secrets: inherit
  deploy-locales:
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[pulumi up]'))
    needs: [ setup-infrastructure, build-api-specs, build-locales ]
    uses: ./.github/workflows/deploy-locales.yml
    secrets: inherit
    with:
      target-environment: dev
      target-domain-name: ${{ needs.setup-infrastructure.outputs.target-domain-name }}
  # Backend
  build-backend:
    uses: ./.github/workflows/build-backend.yml
    needs: [ build-api-specs, setup-infrastructure, deploy-auth ]
    secrets: inherit
  deploy-backend:
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[pulumi up]'))
    needs: [ build-backend, setup-infrastructure, deploy-auth ]
    uses: ./.github/workflows/deploy-backend.yml
    secrets: inherit
    with:
      target-environment: dev
      version-info: ${{ needs.build-backend.outputs.version-info }}
      target-domain-name: ${{ needs.setup-infrastructure.outputs.target-domain-name }}
      user-pool-id: ${{ needs.deploy-auth.outputs.userPoolId }}
      user-pool-client-id: ${{ needs.deploy-auth.outputs.userPoolClientId }}
  smoke-test-backend:
    needs: [ build-backend, deploy-backend ]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: backend
      expected-version-info: ${{ needs.build-backend.outputs.version-info }}
      component-url: ${{ needs.deploy-backend.outputs.backedRestApiURLBase }}
      resources-base-url: ${{ needs.deploy-backend.outputs.resourcesBaseUrl }}
  # Frontend
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    needs: [ build-api-specs, setup-infrastructure, deploy-auth ]
    secrets: inherit
    with:
      target-environment: dev
      backend-url: ${{ needs.setup-infrastructure.outputs.backend-url }}
      locales-url: ${{ needs.setup-infrastructure.outputs.locales-url }}
      auth-url: ${{ needs.setup-infrastructure.outputs.auth-url }}
      cognito-client-id: ${{ needs.deploy-auth.outputs.clientId }}
      cognito-client-secret: ${{ needs.deploy-auth.outputs.clientSecret }}
  deploy-frontend:
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[pulumi up]'))
    needs: [ build-frontend, setup-infrastructure ]
    uses: ./.github/workflows/deploy-frontend.yml
    secrets: inherit
    with:
      target-environment: dev
      version-info: ${{ needs.build-frontend.outputs.version-info }}
      target-domain-name: ${{ needs.setup-infrastructure.outputs.target-domain-name }}
  smoke-test-frontend:
    needs: [ build-frontend, deploy-frontend ]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: frontend
      expected-version-info: ${{ needs.build-frontend.outputs.version-info }}
      component-url: ${{ needs.deploy-frontend.outputs.frontendBucketWebsiteURLBase }}
  # Sonarcloud
  sonarcloud:
    needs: [ build-backend, build-frontend, build-api-specs ]
    uses: ./.github/workflows/sonar-cloud.yml
    secrets: inherit
  # Common Infrastructure
  deploy-common:
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[pulumi up]'))
    needs: [ deploy-frontend, build-frontend, deploy-backend, build-backend, setup-infrastructure, deploy-locales, setup-infrastructure ]
    uses: ./.github/workflows/deploy-common.yml
    secrets: inherit
    with:
      target-environment: dev
      frontend-version-info: ${{ needs.build-frontend.outputs.version-info }}
      backend-version-info: ${{ needs.build-backend.outputs.version-info }}
      base-domain-name: ${{ needs.setup-infrastructure.outputs.base-domain-name }}
  smoke-test-frontend-cdn:
    needs: [ build-frontend, setup-infrastructure, deploy-common ]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: frontend
      expected-version-info: ${{ needs.build-frontend.outputs.version-info }}
      component-url: ${{ needs.deploy-common.outputs.frontendURLBase }}
  smoke-test-backend-cdn:
    needs: [ build-backend, deploy-backend, deploy-common ]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: backend
      expected-version-info: ${{ needs.build-backend.outputs.version-info }}
      resources-base-url: ${{ needs.deploy-backend.outputs.resourcesBaseUrl }}
      component-url: ${{ needs.deploy-common.outputs.backendURLBase }}
