name: Main CI
on:
  push:
  # branches:
  #   - main
  #pull_request:
  #  types: [ opened, synchronize, reopened ]

jobs:
  # Sanitize Branch
  sanitize-branch:
    uses: ./.github/workflows/sanitize-branch.yml
    secrets:  inherit
  deploy-ephemeral:
    if: github.event_name == 'pull_request' && contains(github.event.head_commit.message, '[provision_stack]')
    uses: ./.github/workflows/setup.yml
    secrets: inherit
  # API Specifications
  build-api-specs:
    uses: ./.github/workflows/build-api-specs.yml
    secrets: inherit
  # Backend
  build-backend:
    uses: ./.github/workflows/build-backend.yml
    needs: [ build-api-specs ]
    secrets: inherit
  deploy-backend:
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[pulumi up]'))
    needs: [ build-backend ]
    uses: ./.github/workflows/deploy-backend.yml
    secrets: inherit
    with:
      target-environment: dev
      version-info: ${{ needs.build-backend.outputs.version-info }}
      stack-name: ${{ needs.sanitize-branch.outputs.sanitized_branch }}
  smoke-test-backend:
    needs: [ build-backend, deploy-backend]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: backend
      expected-version-info: ${{ needs.build-backend.outputs.version-info }}
      component-url: ${{ needs.deploy-backend.outputs.backedRestApiURLBase }}
      resources-base-url: ${{ needs.deploy-backend.outputs.resourcesBaseUrl }}
  # Frontend
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    needs: [ build-api-specs ]
    secrets: inherit
  deploy-frontend:
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[pulumi up]'))
    needs: [ build-frontend, sanitize-branch ]
    uses: ./.github/workflows/deploy-frontend.yml
    secrets: inherit
    with:
      target-environment: dev
      version-info: ${{ needs.build-frontend.outputs.version-info }}
      stack-name: ${{ needs.sanitize-branch.outputs.sanitized_branch }}
  smoke-test-frontend:
    needs: [ build-frontend, deploy-frontend]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: frontend
      expected-version-info: ${{ needs.build-frontend.outputs.version-info }}
      component-url: ${{ needs.deploy-frontend.outputs.frontendBucketWebsiteURLBase }}
  # Sonarcloud
  sonarcloud:
    needs: [ build-backend, build-frontend, build-api-specs ]
    uses: ./.github/workflows/sonar-cloud.yml
    secrets: inherit
  # Common Infrastructure
  deploy-common:
    if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[pulumi up]'))
    needs: [ deploy-frontend, build-frontend, deploy-backend, build-backend, sanitize-branch ]
    uses: ./.github/workflows/deploy-common.yml
    secrets: inherit
    with:
      target-environment: dev
      frontend-version-info: ${{ needs.build-frontend.outputs.version-info }}
      backend-version-info: ${{ needs.build-backend.outputs.version-info }}
      stack-name: ${{ needs.sanitize-branch.outputs.sanitized_branch }}
  #  Update the parent Nameserver with the subdomain
  deploy-nameserver:
     if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[pulumi up]'))
     needs: [ deploy-common, sanitize-branch ]
     uses: ./.github/workflows/deploy-nameserver.yml
     secrets: inherit
     with:
       target-environment: dev
       stack-name: ${{ needs.sanitize-branch.outputs.sanitized_branch }}
  smoke-test-frontend-cdn:
    needs: [ build-frontend, deploy-common, deploy-nameserver]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: frontend
      expected-version-info: ${{ needs.build-frontend.outputs.version-info }}
      component-url: ${{ needs.deploy-common.outputs.frontendURLBase }}
  smoke-test-backend-cdn:
    needs: [ build-backend, deploy-backend, deploy-common, deploy-nameserver ]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: backend
      expected-version-info: ${{ needs.build-backend.outputs.version-info }}
      resources-base-url: ${{ needs.deploy-backend.outputs.resourcesBaseUrl }}
      component-url: ${{ needs.deploy-common.outputs.backendURLBase }}
