name: Main CI
on:
  push:
  # branches:
  #   - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  # API Specifications
  build-api-specs:
    uses: ./.github/workflows/build-api-specs.yml
    secrets: inherit
  # Backend
  build-backend:
    uses: ./.github/workflows/build-backend.yml
    needs: [ build-api-specs ]
    secrets: inherit
  deploy-backend:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [ build-backend ]
    uses: ./.github/workflows/deploy-backend.yml
    secrets: inherit
    with:
      target-environment: dev
      version-info: ${{ needs.build-backend.outputs.version-info }}
  smoke-test-backend:
    needs: [ build-backend, deploy-backend]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: backend
      expected-version-info: ${{ needs.build-backend.outputs.version-info }}
      component-url: ${{ needs.deploy-backend.outputs.backedRestApiURLBase }}
  # Frontend
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    needs: [ build-api-specs ]
    secrets: inherit
  deploy-frontend:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [ build-frontend ]
    uses: ./.github/workflows/deploy-frontend.yml
    secrets: inherit
    with:
      target-environment: dev
      version-info: ${{ needs.build-frontend.outputs.version-info }}
  smoke-test-frontend:
    needs: [ build-frontend, deploy-frontend]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: frontend
      expected-version-info: ${{ needs.build-frontend.outputs.version-info }}
      component-url: ${{ needs.deploy-frontend.outputs.frontendBucketWebsiteURLBase }}
  # Sonarcloud
  sonarcloud:
    needs: [ build-backend, build-frontend, build-api-specs ]
    uses: ./.github/workflows/sonar-cloud.yml
    secrets: inherit
  # Common Infrastructure
  deploy-common:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [ deploy-frontend, build-frontend, deploy-backend, build-backend ]
    uses: ./.github/workflows/deploy-common.yml
    secrets: inherit
    with:
      target-environment: dev
      frontend-version-info: ${{ needs.build-frontend.outputs.version-info }}
      backend-version-info: ${{ needs.build-backend.outputs.version-info }}
  smoke-test-frontend-cdn:
    needs: [ build-frontend, deploy-common]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: frontend
      expected-version-info: ${{ needs.build-frontend.outputs.version-info }}
      component-url: ${{ needs.deploy-common.outputs.frontendURLBase }}
  smoke-test-backend-cdn:
    needs: [ build-backend, deploy-common ]
    uses: ./.github/workflows/smoke-test-version.yml
    secrets: inherit
    with:
      component: backend
      expected-version-info: ${{ needs.build-backend.outputs.version-info }}
      component-url: ${{ needs.deploy-common.outputs.backendURLBase }}