name: Main CI
on:
  push:
   # branches:
   #   - main
  #pull_request:
   # types: [opened, synchronize, reopened]

jobs:
  build-frontend:
    uses: ./.github/workflows/fe-workflow.yml
    secrets: inherit
  build-backend:
    uses: ./.github/workflows/backend-build.yml
    secrets: inherit
  deploy-backend:
    needs: [build-backend]
    uses: ./.github/workflows/backend-deploy.yml
    secrets: inherit
    with:
      version-info: ${{ needs.build-backend.outputs.version-info }}
  sonarcloud:
    needs: [build-backend, build-frontend]
    uses: ./.github/workflows/sonar-cloud.yml
    secrets: inherit