name: Main CI
on:
  push:
   # branches:
   #   - main
  #pull_request:
   # types: [opened, synchronize, reopened]

jobs:
  build-frontend:
    uses: ./.github/workflows/fe-workflow.yml
    secrets: inherit
  build-backend:
    uses: ./.github/workflows/be-workflow.yml
    secrets: inherit
  sonarcloud:
    needs: [build-backend, build-frontend]
    uses: ./.github/workflows/sonar-cloud.yml
    secrets: inherit