name: Set up Environment COnfig

on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string

env:
  target-domain: tabiya.tech

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    outputs:
      environment: ${{ inputs.target-environment }}
      target-domain-name: ${{ env.target-name }}-${{ inputs.target-environment }}.${{ env.target-domain }}
      frontend-url: https://${{ inputs.target-environment }}.${{ env.target-domain }}
      backend-url: https://${{ inputs.target-environment }}.${{ env.target-domain }}/api/
      auth-url: https://auth.${{ inputs.target-environment }}.${{ env.target-domain }}
    steps:
      - name: Logging
        run: echo "${{ inputs.target-environment }} environment setup"
