name: Setup Ephemeral Database

on:
  workflow_call:
    inputs:
      stack-name:
        required: true
        type: string

jobs:
  deploy-db:
    runs-on: ubuntu-latest
    environment: ${{ inputs.stack-name }}
    outputs:
      mongo_uri:  ${{ steps.get-branch.outputs.mongo_uri }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MongoDB Atlas
        run: |
          sudo apt-get update
          sudo apt-get install gnupg
          wget -qO - https://pgp.mongodb.com/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-atlas

      - name: Configure MongoDB CLI
        run: |
          atlas config set org_id ${{ secrets.MONGODB_ORG_ID }}
          atlas config set project_id ${{ secrets.MONGODB_PROJECT_ID_NEW }}
          atlas config set public_api_key "${{ secrets.MONGODB_PUBLIC_API_KEY }}"
          atlas config set private_api_key "${{ secrets.MONGODB_PRIVATE_KEY }}"

      - name: Create database
        run: |
          atlas cluster create Cluster0 --projectId ${{ secrets.MONGODB_PROJECT_ID_NEW }} --provider AWS --region US_EAST_1 --tier M0 --output json

      - name: Get connection string
        id: get-branch
        run: |
          sleep 60
          output=$(atlas cluster connectionString describe Cluster0 --output json)
          standardSrv=$(echo "$output" | jq -r '.standardSrv')
          echo "::set-output name=standardSrv::'$mongo_uri/${{ inputs.stack-name }}'"
  # API Specifications
  build-api-specs:
    uses: ./.github/workflows/build-api-specs.yml
    secrets: inherit
  # Backend
  build-backend:
    uses: ./.github/workflows/build-backend.yml
    needs: [ build-api-specs ]
    secrets: inherit
  deploy-backend:
    needs: [ build-backend ]
    uses: ./.github/workflows/deploy-backend.yml