name: Set up Environment COnfig


env:
  target-domain: tabiya.tech

on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
    outputs:
      base-domain-name:
        description: "The base domain name / tabiya domain name"
        value: ${{ jobs.setup.outputs.base-domain-name }}
      target-domain-name:
        description: "The target domain name"
        value: ${{ jobs.setup.outputs.target-domain-name }}
      frontend-url:
        description: "The frontend url"
        value: ${{ jobs.setup.outputs.frontend-url }}
      backend-url:
        description: "The backend url"
        value: ${{ jobs.setup.outputs.backend-url }}
      auth-url:
        description: "The auth url"
        value: ${{ jobs.setup.outputs.auth-url }}
      cognito-client-id:
        description: "The cognito client id"
        value: ${{ jobs.setup.outputs.cognito-client-id }}
      cognito-client-secret:
        description: "The cognito client secret"
        value: ${{ jobs.setup.outputs.cognito-client-secret }}

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    outputs:
      base-domain-name: ${{ env.target-domain }}
      target-domain-name: ${{ inputs.target-environment }}.${{ env.target-domain }}
      frontend-url: https://${{ inputs.target-environment }}.${{ env.target-domain }}
      backend-url: https://${{ inputs.target-environment }}.${{ env.target-domain }}/api
      auth-url: https://auth.${{ inputs.target-environment }}.${{ env.target-domain }}
      cognito-client-id: ${{ vars.COGNITO_CLIENT_ID }}
      cognito-client-secret: ${{ vars.COGNITO_CLIENT_SECRET }}
    steps:
      - name: Logging
        run: | 
          echo "Finished setting up ${{ inputs.target-environment }} environment configuration ${{ vars.COGNITO_CLIENT_ID }} ${{ vars.COGNITO_CLIENT_SECRET }}"
