name: Smoke Test the version of the backend/frontend
on:
  workflow_call:
    inputs:
      name:
        description: The name of the workflow
        required: true
        type: string
      component:
        description: Either 'frontend' or 'backend'
        required: true
        type: string
      resources-base-url:
        description: The api resources base url of the backend
        required: false
        type: string
      component-url:
        description: The urlbase of the 'frontend' or 'backend'
        required: true
        type: string
      expected-version-info:
        description: The expected version info
        required: true
        type: string
jobs:
  smoke-test:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: ${{ inputs.component }}/yarn.lock
      - id: install-dependencies
        shell: bash
        run: yarn install
        working-directory: ${{ inputs.component }}
      - id: smoke-test
        shell: bash
        run: |
          export EXPECTED_VERSION_INFO='${{ inputs.expected-version-info }}'
          export E2E_BASE_URL=${{ inputs.component-url }}
          export E2E_RESOURCES_BASE_URL=${{ inputs.resources-base-url }}
          yarn run test:smoke
        working-directory: ${{ inputs.component }}
